# This is a basic workflow to help you get started with Actions

name: Build_fast

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "bld_gnu_ompi"
  bld_gnu_ompi:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran openmpi-bin libopenmpi-dev

    # Runs a set of commands using the runners shell
    - name: Compile
      run: make BUILD=dev

    - name: Examples
      run: make examples

  bld_intel:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Add Intel OneApi
    - name: setup repo
      run: |
        sudo echo "deb [trusted=yes] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
    # Install dependencies
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install -y intel-oneapi-common-vars intel-oneapi-compiler-fortran intel-oneapi-mkl intel-oneapi-mkl-devel intel-oneapi-mpi intel-oneapi-mpi-devel

    # Runs a set of commands using the runners shell
    - name: Compile
      run: source /opt/intel/oneapi/setvars.sh && make CMP=intel BUILD=debug && make examples

    # Runs a set of commands using the runners shell
    - name: Compile with MKL
      run: source /opt/intel/oneapi/setvars.sh && make CMP=intel FFT=mkl BUILD=debug && make examples
